Pull Request
mgucma/onlinebook pull request #1
Opened 2024-08-12 08:01 UTC by mgucma

2024-08-12 18:16 UTC, beatarjn requested changes

2024-08-12 18:16 UTC, beatarjn commented on src/main/java/com/marek/onlinebookstore/service/impl/BookServiceImpl.java
> +
Pls remove empty line

2024-08-12 18:16 UTC, beatarjn commented on src/main/java/com/marek/onlinebookstore/entity/Book.java
> +
Pls remove empty line

2024-08-12 18:16 UTC, beatarjn commented on src/test/java/com/marek/onlinebookstore/BookRepositoryTests.java
> +
Pls remove empty line

2024-08-12 18:16 UTC, beatarjn commented on src/test/java/com/marek/onlinebookstore/BookRepositoryTests.java
> +    void testCreateReadUpdateDelete() {
Unit tests should be created separately for each method.

2024-08-13 06:42 UTC, mgsorigo commented on src/main/java/com/marek/onlinebookstore/service/impl/BookServiceImpl.java
> +
oki

2024-08-13 16:04 UTC, MateuszRostek approved these changes

2024-08-13 16:04 UTC, MateuszRostek requested changes
Remove all tests.

2024-08-14 15:19 UTC, MateuszRostek approved these changes
Good job

2024-08-15 03:29 UTC, merged